Repository GrantBirki/astrowind, pull requests merged in 2023-08, with the labels that each got.

#199 fix image route collision
  astro.config.mjs
  package-lock.json
  package.json
Labels: bug

#201 npm update
  package-lock.json
Labels: dependencies

#202 source sync
  .prettierignore
  package-lock.json
  package.json
  src/assets/favicons/favicon.ico
  src/assets/favicons/favicon.svg
  src/assets/styles/tailwind.css
  src/components/CustomFonts.astro
  src/components/CustomStyles.astro
  src/components/Favicons.astro
  src/components/common/BasicScripts.astro
  src/components/common/MetaTags.astro
  src/components/widgets/Announcement.astro
  src/components/widgets/CallToAction.astro
  src/components/widgets/Content.astro
  src/components/widgets/DListItem.astro
  src/components/widgets/FAQs.astro
  src/components/widgets/Features.astro
  src/components/widgets/Features2.astro
  src/components/widgets/Footer.astro
  src/components/widgets/Header.astro
  src/components/widgets/Hero.astro
  src/components/widgets/Hero2.astro
  src/components/widgets/Note.astro
  src/components/widgets/Stats.astro
  src/components/widgets/Steps.astro
  src/components/widgets/Steps2.astro
  src/config/components/header.js
  src/content/post/astrowind-template-in-depth.md
  src/content/post/astrowind-template-in-depth.mdx
  src/layouts/BaseLayout.astro
  src/pages/[...blog]/[...page].astro
  src/pages/contact.astro
  src/pages/landing/mobile-app.astro
  src/pages/landing/saas.astro
  src/pages/pricing.astro
  src/pages/services.astro
Labels: enhancement

#203 Snappy Fix - Locations Component
  src/config/components/header.js
  src/config/pages/stores/hero.js
  src/config/pages/stores/locations.js
  src/pages/index.astro
  src/pages/stores.astro
Labels: bug

#204 not-prose - Update Announcement.astro
  src/components/widgets/Announcement.astro
Labels: enhancement

#205 fix 'Team' widget name clash
  src/pages/team.astro
Labels: bug

#206 fix gallery name clash
  src/pages/gallery.astro
Labels: bug

#208 header theme fixes on mobile
  src/assets/styles/tailwind.css
  src/components/widgets/Header.astro
Labels: bug

#209 Source Sync 🔄
  src/types.d.ts
  tailwind.config.cjs
Labels: enhancement

#217 Fix build by removing astro-compress
  astro.config.mjs
  package-lock.json
  package.json
Labels: bug, dependencies
